SELECT T1.CD_PEDIDO,T1.CD_TIPO_OPERACA,T1.DT_PEDIDO,
T1.CD_CLIENTE||' - '||T2.NOME_COMPLETO AS CLIENTE,
T1.CD_REPRESENTANT||' - '|| T3.NOME_COMPLETO AS REPRESENTANTE,
T2.ENDERECO||', '||T2.NUMERO AS RUA,T2.BAIRRO,
T2.MUNICIPIO||' - '||T2.UF AS MUNICIPIO,T2.CEP,
T2.CNPJ_CPF,T2.INSCRICAO,T2.FONE,T2.contato AS CONTATO,
T1.Dt_Prazo_Entreg,
CD_TRANSPORTADO,TRANS.NOME_COMPLETO AS TRANSPORTADORA,
t2.COMPLEMENTO AS COMPLEMENTO,
t2.FAX_FONE AS FAX,
t1.CD_PORTADOR,PORT.NOME AS NOME_PORTAD,
t1.OBSERVACAO,t1.CD_CONDICAO_PAG,DESC_COND_PAGTO,T1.TIPO_FRETE,TRANS.FONE as fone_trans,
TOP.DESCRICAO AS DESC_TOPERA,T1.CD_ORDEM_DE_COM
 FROM FAPEDIDO T1
 JOIN GEEMPRES T2 
 ON T2.CD_EMPRESA=T1.CD_CLIENTE 
 JOIN GEEMPRES T3
 ON T3.CD_EMPRESA=T1.CD_REPRESENTANT
 LEFT JOIN GEEMPRES TRANS ON TRANS.CD_EMPRESA=T1.CD_TRANSPORTADO
 LEFT JOIN GFPORTAD PORT ON PORT.CD_PORTADOR=T1.CD_PORTADOR
 LEFT JOIN GETOPERA TOP ON TOP.CD_TIPO_OPERACA=T1.CD_TIPO_OPERACA